jumpers_list = {
    'Kamil Stoch (POL)': [5, 5, 4],
    'Dawid Kubacki (POL)': [4, 4, 4],
    'Piotr Żyła (POL)': [4, 4, 4],
    'Paweł Wąsek (POL)': [4, 4, 4],
    'Jakub Wolny (POL)': [4, 4, 4],
    'Aleksander Zniszczoł (POL)': [4, 4, 4],
    'Andrzej Stękała (POL)': [4, 4, 4],
    'Karl Geiger (GER)': [4, 4, 4],
    'Ryouyu Kobayashi (JPN)': [4, 4, 4],
    'Halvor Egner Granerud (NOR)': [4, 4, 4],
    'Anze Lanisek (SLO)': [4, 4, 4],
    'Stefan Kraft (AUT)': [4, 4, 4],
    'Marius Lindvik (NOR)': [4, 4, 4],
    'Markus Eisenbichler (GER)': [4, 4, 4],
    'Kilian Peier (SUI)': [4, 4, 4],
    'Cene Prevc (SLO)': [4, 4, 4],
    'Jan Hoerl (AUT)': [4, 4, 4],
    'Robert Johansson (NOR)': [4, 4, 4],
    'Timi Zajc (SLO)': [4, 4, 4],
    'Pius Paschke (GER)': [4, 4, 4],
    'Constantin Schmid (GER)': [4, 4, 4],
    'Johann Andre Forfang (NOR)': [4, 4, 4],
    'Manuel Fettner (AUT)': [4, 4, 4],
    'Naoki Nakamura (JPN)': [4, 4, 4],
    'Daniel Huber (AUT)': [4, 4, 4],
    'Daniel-Andre Tande (NOR)': [4, 4, 4],
    'Stephan Leyhe (GER)': [4, 4, 4],
    'Andreas Wellinger (GER)': [4, 4, 4],
    'Yukiya Sato (JPN)': [4, 4, 4],
    'Junshiro Kobayashi (JPN)': [4, 4, 4],
    'Stefan Hula (POL)': [4, 4, 4],
    'Jewgienij Klimow (RUS)': [4, 4, 4],
    'Peter Prevc (SLO)': [4, 4, 4],
    'Danił Sadrejew (RUS)': [4, 4, 4],
    'Lovro Kos (SLO)': [4, 4, 4],
    'Philipp Aschenwald (AUT)': [4, 4, 4],
    'Daniel Tschofenig (AUT)': [4, 4, 4],
    'Daiki Ito (JPN)': [4, 4, 4],
    'Gregor Deschwanden (SUI)': [4, 4, 4],
    'Markus Schiffner (AUT)': [4, 4, 4],
    'Simon Ammann (SUI)': [4, 4, 4],
    'Dominik Peter (SUI)': [4, 4, 4],
    'Niko Kytosaho (FIN)': [4, 4, 4],
    'Roman Siergiejewicz Trofimow (RUS)': [4, 4, 4],
    'Fredrik Villumstad (NOR)': [4, 4, 4],
    'Artti Aigro (EST)': [4, 4, 4],
    'Keiichi Sato (JPN)': [4, 4, 4],
    'Michaił Nazarow (RUS)': [4, 4, 4],
    'Władimir Zografski (BUL)': [4, 4, 4],
    'Anders Fannemel (NOR)': [4, 4, 4],
    'Mackenzie Boyd-Clowes (CAN)': [4, 4, 4],
}